const capstoneTitles = [
    "Automated Healthcare System for Remote Monitoring",
    "Smart Home Automation Using IoT",
    "Blockchain-Based Supply Chain Management",
    "Data Analysis and Visualization Tool for Business",
    "Augmented Reality Educational App",
    "Predictive Maintenance System for Industrial Equipment",
    "E-Commerce Platform with Recommendation System",
    "Social Networking App for Professionals",
    "Cybersecurity Incident Response System",
    "AI-Powered Customer Support Chatbot",
    "Intelligent Traffic Management System",
    "Online Learning Platform with Personalized Curriculum",
    "Virtual Reality Training Simulation for Emergency Responders",
    "Mobile App for Language Translation and Learning",
    "Predictive Analytics for Stock Market Forecasting",
    "Automated Agricultural Monitoring System",
    "IoT-Based Environmental Monitoring Solution",
    "Smart City Traffic Control System",
    "Telemedicine Platform for Remote Consultations",
    "Digital Wallet and Cryptocurrency Management App",
     "Automated Healthcare System for Remote Monitoring",
     "Smart Home Automation Using IoT",
     "Blockchain-Based Supply Chain Management",
     "Data Analysis and Visualization Tool for Business",
     "Augmented Reality Educational App",
     "Predictive Maintenance System for Industrial Equipment",
     "E-Commerce Platform with Recommendation System",
     "Social Networking App for Professionals",
     "Cybersecurity Incident Response System",
     "AI-Powered Customer Support Chatbot",
     "Intelligent Traffic Management System",
     "Online Learning Platform with Personalized Curriculum",
     "Virtual Reality Training Simulation for Emergency Responders",
     "Mobile App for Language Translation and Learning",
     "Predictive Analytics for Stock Market Forecasting",
     "Automated Agricultural Monitoring System",
     "IoT-Based Environmental Monitoring Solution",
     "Smart City Traffic Control System",
     "Telemedicine Platform for Remote Consultations",
     "Digital Wallet and Cryptocurrency Management App",
     "Interactive Museum Guide App with AR Features",
     "Automated Attendance Management System for Schools",
     "Online Food Delivery Service with Real-Time Tracking",
     "Smart Fitness Tracker and Health Monitoring App",
     "AI-Based Personal Finance Assistant",
     "Smart Car Parking System with IoT Integration",
     "Interactive Virtual Campus Tour for Universities",
     "AI-Powered Language Translation Service",
     "Automated Inventory Management System for Retailers",
     "Energy-Efficient Home Automation System",
     "Smart Waste Management System Using IoT",
     "Mobile App for Mental Health Support and Counseling",
     "Augmented Reality Fashion Shopping Experience",
     "AI-Based Personalized News Recommendation Service",
     "Automated Disaster Response System",
     "Elderly Care Monitoring System with Wearable Devices",
     "Virtual Interior Design and Home Decor Planning App",
     "AI-Enhanced Video Editing Software",
     "Blockchain-Based Digital Voting System",
     "Personalized Travel Itinerary Planner App",
     "AI-Based Music Composition and Remixing Tool",
       "Automated Healthcare System for Remote Monitoring",
       "Smart Home Automation Using IoT",
       "Blockchain-Based Supply Chain Management",
       "Data Analysis and Visualization Tool for Business",
       "Augmented Reality Educational App",
       "Predictive Maintenance System for Industrial Equipment",
       "E-Commerce Platform with Recommendation System",
       "Social Networking App for Professionals",
       "Cybersecurity Incident Response System",
       "AI-Powered Customer Support Chatbot",
       "Intelligent Traffic Management System",
       "Online Learning Platform with Personalized Curriculum",
       "Virtual Reality Training Simulation for Emergency Responders",
       "Mobile App for Language Translation and Learning",
       "Predictive Analytics for Stock Market Forecasting",
       "Automated Agricultural Monitoring System",
       "IoT-Based Environmental Monitoring Solution",
       "Smart City Traffic Control System",
       "Telemedicine Platform for Remote Consultations",
       "Digital Wallet and Cryptocurrency Management App",
       "Interactive Museum Guide App with AR Features",
       "Automated Attendance Management System for Schools",
       "Online Food Delivery Service with Real-Time Tracking",
       "Smart Fitness Tracker and Health Monitoring App",
       "AI-Based Personal Finance Assistant",
       "Smart Car Parking System with IoT Integration",
       "Interactive Virtual Campus Tour for Universities",
       "AI-Powered Language Translation Service",
       "Automated Inventory Management System for Retailers",
       "Energy-Efficient Home Automation System",
       "Smart Waste Management System Using IoT",
       "Mobile App for Mental Health Support and Counseling",
       "Augmented Reality Fashion Shopping Experience",
       "AI-Based Personalized News Recommendation Service",
       "Automated Disaster Response System",
       "Elderly Care Monitoring System with Wearable Devices",
       "Virtual Interior Design and Home Decor Planning App",
       "AI-Enhanced Video Editing Software",
       "Blockchain-Based Digital Voting System",
       "Personalized Travel Itinerary Planner App",
       "AI-Based Music Composition and Remixing Tool",
       "Automated Language Learning Platform with Speech Recognition",
       "Blockchain-Based Certificate Verification System",
       "AI-Powered Agricultural Crop Monitoring System",
       "Smart Classroom Management System for Teachers",
       "Interactive Language Learning Game App",
       "AI-Based Fraud Detection System for Financial Transactions",
       "Blockchain-Based Digital Identity Verification Platform",
       "Smart Public Transportation Management System",
       "AI-Powered Speech Recognition and Transcription Service",
       "Virtual Reality Therapy for Phobias and Anxiety",
       "Automated Garbage Collection and Recycling System",
       "AI-Based Personalized Recipe Recommendation App",
       "Blockchain-Based Royalty Management System for Artists",
       "Smart Parking System with Real-Time Availability Updates",
       "AI-Powered Health Diagnosis Chatbot",
       "Virtual Reality Historical Tours for Museums and Landmarks",
       "Blockchain-Based Academic Credential Verification System",
       "Offline ChatAI Learning Bot",
       "Enhancing Web Application Security: A Comprehensive Study of Common Vulnerabilities and Defense Mechanisms",
       "Optimizing Database Performance: Strategies for Efficient Query Processing",
       "Developing a Scalable Microservices Architecture: Challenges and Best Practices",
       "Machine Learning Algorithms for Predictive Code Analytics: A Comparative Analysis",
       "Building a Cross-Platform Mobile Application: Challenges and Solutions",
       "Exploring the Potential of Progressive Web Apps for Enhanced User Experience",
       "DevOps Implementation in Software Development: Continuous Integration and Deployment",
       "Game Development with Unity: Creating Immersive Experiences for Different Platforms",
       "Serverless Computing: Architectural Patterns and Practical Implementations",
       "Code Refactoring Techniques: Improving Software Maintainability and Readability",
       "Blockchain-Based Smart Contracts: Implementation and Use Cases",
       "Developing a Real-Time Chat Application: Technologies and Performance Optimization",
       "Testing Automation Frameworks: Tools and Best Practices",
       "Natural Language Processing in Programming: Building Intelligent Code Assistants",
       "Implementing Cloud-Native Applications: Containers, Orchestration, and Beyond",
       "WebAssembly: Revolutionizing Web Development with High-Performance Code Execution",
       "Automated Bug Detection and Fixing: Leveraging Machine Learning Techniques",
       "Building a RESTful API: Design Patterns and Performance Optimization",
       "Integrated Hospital Management System: Streamlining Patient Care and Administrative Processes",
       "Smart Home Automation System: Enhancing Comfort, Security, and Energy Efficiency",
       "Enterprise Resource Planning (ERP) Implementation: Optimizing Business Operations",
       "Automated Inventory Management System: Real-time Tracking and Optimization",
       "Online Banking System with Advanced Security Features: Ensuring Safe Transactions",
       "Smart Classroom Management System: Improving Learning Environments through Technology",
       "Intelligent Traffic Management System: Alleviating Urban Traffic Congestion",
       "E-Commerce Order Fulfillment System: Efficient Processing and Delivery",
       "Library Management System: Organizing and Digitizing Library Resources","Automated Attendance Tracking System: Enhancing Accuracy and Efficiency",
       "Fleet Management System: Optimizing Vehicle Operations and Maintenance",
       "Computerized Point of Sale (POS) System: Simplifying Retail Transactions"
];

const generateButton = document.getElementById("generateButton");
const titleDisplay = document.getElementById("titleDisplay");

function generateRandomTitle() {
  const randomIndex = Math.floor(Math.random() * capstoneTitles.length);
  const randomTitle = capstoneTitles[randomIndex];
  return randomTitle;
}

generateButton.addEventListener("click", function() {
  const generatedTitle = generateRandomTitle();
  titleDisplay.textContent = "" + generatedTitle;
});